# -*- coding: utf-8 -*-
import json

a = json.loads("""
{
	"hr": 0,
	"message": "成功",
	"extraData": null,
	"data": {
		"filter": null,
		"total": 0,
		"rows": [
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "当前时间的非期末考试",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 0,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1577958900000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1672565100000,
				"questionCount": null,
				"id": "1_252"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "期末考试 已提交 已经批改",
				"studentScore": 44.6,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 2,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556208000000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556211600000,
				"questionCount": null,
				"id": "1_129"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "期末考试 已提交 未批改",
				"studentScore": 17.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556262000000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1648972800000,
				"questionCount": null,
				"id": "1_144"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的期末考试",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1893427200000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1930084200000,
				"questionCount": null,
				"id": "1_189"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的补考（总评）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1672416000000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1672419600000,
				"questionCount": null,
				"id": "3_5"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的补考（期末成绩）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1672423200000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1672426800000,
				"questionCount": null,
				"id": "3_6"
			},
			{
				"totalTime": 3600,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的非期末考试",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1735724400000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1767202800000,
				"questionCount": null,
				"id": "1_245"
			},
			{
				"totalTime": 120,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "自动化测试作业",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": null,
				"type": 2,
				"totalScore": 100,
				"endTime": null,
				"questionCount": null,
				"id": "2_282"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "非期末考试 已提交 已批改",
				"studentScore": 44.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 2,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556266800000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556267400000,
				"questionCount": null,
				"id": "1_174"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "非期末考试 已提交 未批改",
				"studentScore": 17.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556265600000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556266200000,
				"questionCount": null,
				"id": "1_159"
			}
		]
	}
}
""")

b = json.loads("""
{
	"hr": 0,
	"message": "成功",
	"extraData": null,
	"data": {
		"filter": null,
		"total": 0,
		"rows": [
			{
				"totalTime": 3600,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已批改的补考",
				"studentScore": 31.8,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 2,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1572537600000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1736058300000,
				"questionCount": null,
				"id": "3_9"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的期末(提交过)",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1483262700000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1485795900000,
				"questionCount": null,
				"id": "1_250"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的期末(未提交过)",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1514741100000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1515057900000,
				"questionCount": null,
				"id": "1_251"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的期末考试",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1546272000000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1546358400000,
				"questionCount": null,
				"id": "1_99"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的补考（总评）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1543507200000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1543510800000,
				"questionCount": null,
				"id": "3_3"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的补考（期末成绩）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1543514400000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1543518000000,
				"questionCount": null,
				"id": "3_4"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的非期末(未提交过)",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1388568300000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1420104300000,
				"questionCount": null,
				"id": "1_249"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "已过时间的非期末考试(提交过)",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1546358400000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1546444800000,
				"questionCount": null,
				"id": "1_114"
			},
			{
				"totalTime": 3600,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "当前时间的补考1",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1572537600000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1735574400000,
				"questionCount": null,
				"id": "3_10"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "当前时间的补考（总评）",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 0,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1546185600000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1669824000000,
				"questionCount": null,
				"id": "3_7"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "当前时间的补考（期末成绩）",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1546185600000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1640880000000,
				"questionCount": null,
				"id": "3_8"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "当前时间的非期末考试",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 0,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1577958900000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1672565100000,
				"questionCount": null,
				"id": "1_252"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "期末考试 已提交 已经批改",
				"studentScore": 44.6,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 2,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556208000000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556211600000,
				"questionCount": null,
				"id": "1_129"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "期末考试 已提交 未批改",
				"studentScore": 17.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556262000000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1648972800000,
				"questionCount": null,
				"id": "1_144"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的期末考试",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1893427200000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1930084200000,
				"questionCount": null,
				"id": "1_189"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的补考（总评）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1672416000000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1672419600000,
				"questionCount": null,
				"id": "3_5"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的补考（期末成绩）",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": -1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1672423200000,
				"type": 3,
				"totalScore": 100,
				"endTime": 1672426800000,
				"questionCount": null,
				"id": "3_6"
			},
			{
				"totalTime": 3600,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "未到时间的非期末考试",
				"studentScore": null,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": null,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1735724400000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1767202800000,
				"questionCount": null,
				"id": "1_245"
			},
			{
				"totalTime": 120,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "自动化测试作业",
				"studentScore": 0.0,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": null,
				"type": 2,
				"totalScore": 100,
				"endTime": null,
				"questionCount": null,
				"id": "2_282"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "非期末考试 已提交 已批改",
				"studentScore": 44.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 2,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556266800000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556267400000,
				"questionCount": null,
				"id": "1_174"
			},
			{
				"totalTime": 7200,
				"answeredCount": null,
				"timeSpend": "null",
				"title": "非期末考试 已提交 未批改",
				"studentScore": 17.7,
				"quizTags": null,
				"free": true,
				"objectiveQuestionScore": null,
				"answerStatus": 1,
				"submitTime": "null",
				"correctCount": null,
				"startTime": 1556265600000,
				"type": 1,
				"totalScore": 100,
				"endTime": 1556266200000,
				"questionCount": null,
				"id": "1_159"
			}
		]
	}
}
""")


def ordered(obj):
    if isinstance(obj, dict):
        return sorted((k, ordered(v)) for k, v in obj.items())
    if isinstance(obj, list):
        return sorted(ordered(x) for x in obj)
    else:
        return obj


print(ordered(a) == ordered(b))