# -*- coding: utf-8 -*-
import os
import json
dict_temp = {
    "init": "",
    "添加": "__block BOOL isSuccessful=NO;\n FMDatabaseQueue *databaseQueue=[ELDatabaseQueueHelper singletonDatabaseQueue];\n [databaseQueue inDatabase:^(FMDatabase *db) {\n isSuccessful = [db executeUpdate:@\"INSERT INTO MediaPlayPosition_V3(SchoolId,PeriodId,UserId,UserClassId,ClassId,CourseId,LessonId,UniqueId,Position,RecordDate,Duration) VALUES(?,?,?,?,?,?,?,?,?,?,?)\",[NSNumber numberWithInteger:mediaPlayPositionRecord.schoolId],[NSNumber numberWithInteger:mediaPlayPositionRecord.periodId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userClassId],[NSNumber numberWithInteger:mediaPlayPositionRecord.classId],[Utility excludeNullValue:mediaPlayPositionRecord.courseId],[NSNumber numberWithInteger:mediaPlayPositionRecord.lessonId],mediaPlayPositionRecord.uniqueId,[NSNumber numberWithFloat:mediaPlayPositionRecord.position],[NSNumber numberWithDouble:mediaPlayPositionRecord.recordDate],[NSNumber numberWithFloat:mediaPlayPositionRecord.duration]];\n }];\n return isSuccessful;",
    "删除": "__block BOOL result;\nFMDatabaseQueue *databaseQueue = [ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase * _Nonnull db) {\nresult = [db executeUpdate:@\"DELETE FROM MediaPlayPosition_V3 WHERE SchoolId=? AND PeriodId=? AND UserId=? AND UserClassId=? AND ClassId=? AND CourseId=?\", [NSNumber numberWithInteger:mediaPlayPositionRecord.schoolId],[NSNumber numberWithInteger:mediaPlayPositionRecord.periodId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userClassId],[NSNumber numberWithInteger:mediaPlayPositionRecord.classId],[Utility excludeNullValue:mediaPlayPositionRecord.courseId]];\n}];\nreturn result;",
    "更新": "__block BOOL isSuccessful=NO;\nFMDatabaseQueue *databaseQueue=[ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase *db) {\nNSInteger recordId = [db intForQuery:@\"SELECT Id FROM MediaUploadData_V1_1 WHERE SchoolId=? AND UserId=? AND ClassId=? AND CourseId=? AND KnowledgeId=? AND QuizId=? AND QuestionId=?\",[NSNumber numberWithInteger:mediaUploadItem.schoolId],[NSNumber numberWithInteger:mediaUploadItem.userId],[NSNumber numberWithInteger:mediaUploadItem.classId],[Utility excludeNullValue:mediaUploadItem.courseId],[NSNumber numberWithInteger:mediaUploadItem.knowledgeId],mediaUploadItem.quizId,mediaUploadItem.questionId];\nif(recordId == 0){\nisSuccessful = [db executeUpdate:@\"INSERT INTO MediaUploadData_V1_1(SchoolId,UserId,ClassId,CourseId,KnowledgeId,QuizId,QuestionId,LocalFilePath,Url,UploadStatus,IsSubmited) VALUES(?,?,?,?,?,?,?,?,?,?,?)\",[NSNumber numberWithInteger:mediaUploadItem.schoolId],[NSNumber numberWithInteger:mediaUploadItem.userId],[NSNumber numberWithInteger:mediaUploadItem.classId],[Utility excludeNullValue:mediaUploadItem.courseId],[NSNumber numberWithInteger:mediaUploadItem.knowledgeId],mediaUploadItem.quizId,mediaUploadItem.questionId,mediaUploadItem.localFilePath,mediaUploadItem.url,[NSNumber numberWithInt:mediaUploadItem.uploadStatus],[NSNumber numberWithBool:mediaUploadItem.isSubmited]];\n}else{\nisSuccessful = [db executeUpdate:@\"UPDATE MediaUploadData_V1_1 SET LocalFilePath=?,Url=?,UploadStatus=?,IsSubmited=?WHERE Id=?\",mediaUploadItem.localFilePath,mediaUploadItem.url,[NSNumber numberWithInt:mediaUploadItem.uploadStatus],[NSNumber numberWithBool:mediaUploadItem.isSubmited],[NSNumber numberWithInteger:recordId]];\n}\n}];\nreturn isSuccessful;",
    "查询多个值": " __block NSString *videoId;\nFMDatabaseQueue *databaseQueue=[ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase *db) {\nFMResultSet *queryResultSet = [db executeQuery:@\"SELECT UniqueId, RecordDate, Position, Duration FROM MediaPlayPosition_V3 WHERE SchoolId=? AND PeriodId=? AND UserId=? AND UserClassId=? AND ClassId=? AND CourseId=? AND LessonId=? AND Position > 0 ORDER BY RecordDate DESC LIMIT 1\",[NSNumber numberWithInteger:mediaPlayPositionRecord.schoolId],[NSNumber numberWithInteger:mediaPlayPositionRecord.periodId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userClassId],[NSNumber numberWithInteger:mediaPlayPositionRecord.classId],[Utility excludeNullValue:mediaPlayPositionRecord.courseId],[NSNumber numberWithInteger:mediaPlayPositionRecord.lessonId]];\nwhile ([queryResultSet next])\n{\nvideoId = [queryResultSet stringForColumnIndex:0];\n}\n[queryResultSet close];\n}];\nreturn videoId;",
    "查询单个值": "\n__block float position = 0;\nFMDatabaseQueue *databaseQueue=[ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase *db) {\nposition = [db doubleForQuery:@\"SELECT Position FROM MediaPlayPosition_V3 WHERE SchoolId=? AND PeriodId=? AND UserId=? AND UserClassId=? AND ClassId=? AND CourseId=? AND LessonId=? AND UniqueId=?\",[NSNumber numberWithInteger:mediaPlayPositionRecord.schoolId],[NSNumber numberWithInteger:mediaPlayPositionRecord.periodId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userId],[NSNumber numberWithInteger:mediaPlayPositionRecord.userClassId],[NSNumber numberWithInteger:mediaPlayPositionRecord.classId],[Utility excludeNullValue:mediaPlayPositionRecord.courseId],[NSNumber numberWithInteger:mediaPlayPositionRecord.lessonId],mediaPlayPositionRecord.uniqueId];\n}];\nreturn position;\n",
    "查询多个对象": " NSMutableArray *quizTags = [[NSMutableArray alloc] init];\nFMDatabaseQueue *databaseQueue = [ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase *db) {\nFMResultSet *queryResultSet = [db executeQuery:@\"SELECT TagId,Title FROM QuizTag_V1_1 WHERE UserId=? AND SchoolId=? AND ClassId=? AND CourseId=? AND LessonId=? AND QuizId=?\",[NSNumber numberWithInteger:userId],[NSNumber numberWithInteger:schoolId],[NSNumber numberWithInteger:classId],[Utility excludeNullValue:courseId],[NSNumber numberWithInteger:lessonId],quizId];\nwhile ([queryResultSet next])\n{\nELQuizTag *tag = [[ELQuizTag alloc] init];\ntag.tagId = [queryResultSet longForColumnIndex:0];\ntag.title = [queryResultSet stringForColumnIndex:1];\n[quizTags addObject:tag];\n}\n[queryResultSet close];\n}];\nreturn quizTags;",
    '字段的增加修改': " FMDatabaseQueue *databaseQueue=[ELDatabaseQueueHelper singletonDatabaseQueue];\n[databaseQueue inDatabase:^(FMDatabase *db) {\nif(![db columnExists:@'CourseId_V1' inTableWithName:@'StudyRecord_V7']) {\n[db beginTransaction];\nBOOL isSuccessful = [db executeUpdate:@'ALTER TABLE StudyRecord_V7 ADD COLUMN CourseId_V1 TEXT'];\nif(isSuccessful)\n{\nisSuccessful = [db executeUpdate:@'UPDATE StudyRecord_V7 SET CourseId_V1 = CourseId'];\n}\nif (isSuccessful) {\n[db commit];\n} else {\n[db rollback];\n}\n}\n}];",
}

file = open("UIFilePath.txt", 'r')
dict = json.loads(file.read())
myFile = dict["数据库"]

if os.path.exists(myFile):
    os.remove(myFile)
file = open(myFile, 'w')
file.write(json.dumps(dict_temp))
# 注意关闭文件
file.close()

file = open(myFile, 'r')
dict = json.loads(file.read())
print(dict)
print(dict["init"])
# 注意关闭文件
file.close()